name: Test deployment

on:
  pull_request:
    branches:
      - master
jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: clean node_modules
        run: rm -rf node_modules
      - name: Install dependencies
        run: npm install
      - name: Test build website
        run: npm run-script build